### Quiz

#### Q1. 다음과 같은 리스트를 이용하여 넘파이 배열을 만들고
전체 갯수, 차원, 데이터형, 구조를 출력하여라
```

['강아지', '원숭이', '꽃', '45', '100']

array(['강아지', '원숭이', '꽃', '45', '100'], dtype='<U3')
차원 ? 1
전체 갯수 ? 5
데이터형 ? <U3
전체 구조  ? (5,)
```

In [1]:
import numpy as np
data = ['강아지', '원숭이', '꽃', '45', '100']
numpy_array=np.array(data)
print('차원 ? ', numpy_array.ndim)
print('전체 갯수 ? ',numpy_array.size)
print('데이터형 ? ',numpy_array.dtype)
print('전체 구조 ? ', numpy_array. shape)

차원 ?  1
전체 갯수 ?  5
데이터형 ?  <U3
전체 구조 ?  (5,)


#### Q2. np.ones()를 이용하여
2행 3열의 넘파이 배열을 생성하여라

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
import numpy as np
numpy_array=np.ones((2,3)) # 인자로 튜플 들어가야 함
print(numpy_array)

[[1. 1. 1.]
 [1. 1. 1.]]


#### Q3. np.arange(), np.reshape()를 이용하여
다음과 같은 넘파이 배열을 생성하여라
```
array([[51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60],
       [61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70],
       [71, 72, 73, 74, 75],
       [76, 77, 78, 79, 80]])
```

In [6]:
import numpy as np
numpy_array=np.arange(51,81)
new_array=np.reshape(numpy_array, (6,5))
print(new_array)

[[51 52 53 54 55]
 [56 57 58 59 60]
 [61 62 63 64 65]
 [66 67 68 69 70]
 [71 72 73 74 75]
 [76 77 78 79 80]]


#### Q4. Q3의 넘파이 배열의 자료형을
float로 변경하고 데이터형을 출력하여라
```
array([[51., 52., 53., 54., 55.],
       [56., 57., 58., 59., 60.],
       [61., 62., 63., 64., 65.],
       [66., 67., 68., 69., 70.],
       [71., 72., 73., 74., 75.],
       [76., 77., 78., 79., 80.]])
```
-------------------------------------  

dtype('float64')

In [7]:
import numpy as np
numpy_array=np.arange(51,81)
new_array=np.reshape(numpy_array, (6,5))
new_array_float=new_array.astype(float) #자료형 변경
print(new_array_float.dtype)

float64


#### Q5. 다음과 같이 넘파이 배열을 생성한 후 1차원 배열로 변경하고 슬라이싱하여라 

```
array([[ 1,  4,  5,  6],
       [56, 23, 45, 67],
       [ 8,  4,  6, 10]])
       
array([ 1,  4,  5,  6, 56, 23, 45, 67,  8,  4,  6, 10])


array([23, 45, 67,  8,  4,  6])
```       

In [8]:
import numpy as np
numpy_array=np.array([[1, 4, 5, 6],
                    [56, 23, 45, 67],
                    [8, 4, 6, 10]])
new_array= numpy_array.flatten()
print(new_array)
sliced_array=new_array[5:]
print(sliced_array)

[ 1  4  5  6 56 23 45 67  8  4  6 10]
[23 45 67  8  4  6 10]


#### Q6. 다음과 같은 넘파이 배열을 생성한 후 아이템을 교체하여라 

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([10,  2,  3,  4,  5,  6,  7,  0,  0,  0])

```

In [12]:
import numpy as np
numpy_array = np.arange(11)
print(numpy_array)
numpy_array[0]=10 #아이템 교체
numpy_array[7:10]=0
print(numpy_array)

[ 0  1  2  3  4  5  6  7  8  9 10]
[10  1  2  3  4  5  6  0  0  0 10]


#### Q7. 2자리의 숫자로 구성된 넘파이 배열(5행5열)을 만들어라. 숫자는 난수를 이용한다. 

```
[[63 85 71 67 15]
 [31 81 69 17 97]
 [25 41 33 23 39]
 [39 43 59 33 43]
 [23 51 65 91 23]]

```

In [14]:
import numpy as np
numpy_array=np.random.randint(11, 100, size=(5,5)) #수 범위, 배열
print(numpy_array)

[[99 23 88 78 61]
 [13 71 89 60 81]
 [28 13 16 19 64]
 [89 86 47 91 63]
 [13 77 57 81 41]]


#### Q8. 1~100 사이의 정수중 7개의 숫자를 무작위로 추출한 후 가장 큰값과 가장 작은 값을 출력하여라.
[91, 65, 14, 66, 65, 98, 34]

max = 98
min = 14

In [18]:
import numpy as np
numpy_array=np.random.randint(1, 101, size=(7,))
print(numpy_array)
print('max = ', np.max(numpy_array), 'min = ', np.min(numpy_array))

[34 67 57 62 29 71 37]
max =  71 min =  29


#### Q9. 다음과 같은 3개의 넘파이 배열을 생성한 후 다음과 같이 합쳐라
```
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]


[[11, 12, 13],
 [14, 15, 16],
 [17, 18, 19]]


[[21, 22, 23],
 [24, 25, 26],
 [27, 28, 29]]
```
 ----------
  Result1 
```
 [[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
  [ 4,  5,  6, 14, 15, 16, 24, 25, 26],
  [ 7,  8,  9, 17, 18, 19, 27, 28, 29]] 
```

  ----------
  Result2
```
 [[ 1,  2,  3],
  [ 4,  5,  6],
  [ 7,  8,  9],
  [11, 12, 13],
  [14, 15, 16],
  [17, 18, 19],
  [21, 22, 23],
  [24, 25, 26],
  [27, 28, 29]]
```

In [32]:
import numpy as np
array_1=np.arange(1,10).reshape(3,3)
print(array_1)
print('\n')
array_2=np.arange(11,20).reshape(3,3)
print(array_2)
print('\n')
array_3=np.arange(21,30).reshape(3,3)
print(array_3)
print('\n')
result1=np.concatenate((array_1,array_2,array_3),axis=1) #열로 합침
print(result1)
print('\n')
result2=np.concatenate((array_1,array_2,array_3),axis=0) #행으로 합침
print(result2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[11 12 13]
 [14 15 16]
 [17 18 19]]


[[21 22 23]
 [24 25 26]
 [27 28 29]]


[[ 1  2  3 11 12 13 21 22 23]
 [ 4  5  6 14 15 16 24 25 26]
 [ 7  8  9 17 18 19 27 28 29]]


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [21 22 23]
 [24 25 26]
 [27 28 29]]


#### Q10. 아래와 같이 넘파이 배열을 생성한 후 50보다 큰 숫자만 필터링하여라. 

```
arr = np.random.choice(100, 40, replace=False)

Before => 

[40, 63,  8,  2, 35, 84, 72, 48, 78, 86, 87, 58,  0, 49, 14, 55, 11,
       73, 39, 26, 75, 27, 99, 46, 25, 22, 34, 83, 24, 47, 31, 57, 62, 19,
       36, 15, 17, 10, 98, 90]

After =>

[63, 84, 72, 78, 86, 87, 58, 55, 73, 75, 99, 83, 57, 62, 98, 90]

```

In [33]:
arr = np.random.choice(100,40, replace=False) #0-99 숫자 중 중복 없이 선택하여 배열 생성
print('Before =>\n', arr)
filtered_arr=arr[arr>50]
print('After =>\n', filtered_arr)

Before =>
 [77 48 50 90 22 64 10 69 75 53 70 71 18  1 24 27 47 88 67  4 83 12 55 25
  7 32 30 74 31 72 81 39 35 80 91 92 33 17 61 84]
After =>
 [77 90 64 69 75 53 70 71 88 67 83 55 74 72 81 80 91 92 61 84]


#### Quiz 11
```
kor = np.array( [60,55,70,30,20,90])
1. 국어점수가 가장큰값을 구하여라
2. 국어점수가 80점이상인 값을 구하여라
3. 국어 점수가 50점이상 80점 이하인 값을 구하여라
4. 국어점수의 평균을 구하여라
5. 국어점수의 총합을 구하여라.
6. 국어점수가 40점이하인 데이터를 삭제하여라
7. 국어점수가 50점이상인 데이터에 가산점 10%를 부여하여라
8. 국어점수 top 3를 구하여라
9. 국어점수가 70점이상이면 '합격' , 아니면 '불합격으로' 아래와 같이 출력하시요

60 '불합격'
55 '불합격'
```

In [57]:
#1
import numpy as np
kor=np.array([60,55,70,30,20,90])
print (np.max(kor))

90


In [58]:
#2
import numpy as np
kor=np.array([60,55,70,30,20,90])
kor_1=kor[kor>=80]
print(kor_1)

[90]


In [60]:
#3
import numpy as np
kor=np.array([60,55,70,30,20,90])
kor_2=kor[(50<=kor)&(kor<=80)]
print(kor_2)

[60 55 70]


In [61]:
#4
import numpy as np
kor=np.array([60,55,70,30,20,90])
print(np.average(kor))

54.166666666666664


In [62]:
#5
import numpy as np
kor=np.array([60,55,70,30,20,90])
print(np.sum(kor))

325


In [63]:
#6
import numpy as np
kor=np.array([60,55,70,30,20,90])
kor_3=kor<=40
kor_4=np.delete(kor,np.where(kor_3)) #kor에서 40점 이하 삭제
print(kor_4)

[60 55 70 90]


In [65]:
#7
import numpy as np
kor=np.array([60,55,70,30,20,90])
kor=kor.astype(float) #정수형에서는 오류 발생, 실수화
kor[kor>=50] += kor[kor>=50]*0.1
print(kor)

[66.  60.5 77.  30.  20.  99. ]


In [75]:
#8
import numpy as np
kor=np.array([60,55,70,30,20,90])
kor_1=np.sort(kor) #정렬
kor_2=kor_1[-3:][::-1] #뒤에서 3개의 원소 선택 후, 역순 나열
print(kor_2)

[90 70 60]


In [81]:
#9
import numpy as np
kor=np.array([60,55,70,30,20,90])
for score in kor:
    result='합격' if score >= 70 else '불합격'
    print(f"{score} '{result}'") #f스트링, 따옴표 안겹치게 구분

60 '불합격'
55 '불합격'
70 '합격'
30 '불합격'
20 '불합격'
90 '합격'
